'use client';

import { AnimatePresence, motion } from 'framer-motion';
import {
  Activity, Archive, ArrowRight, Bell, Check, ChevronDown, CircleHelp, Clock3,
  FileText, Gauge, Globe2, LayoutDashboard, Link2, ListFilter, Mail, Menu,
  MoreHorizontal, Search, Settings, Sparkles, UploadCloud, X, Zap,
} from 'lucide-react';
import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from 'react';

type Target = { id:string; campaignId:string; url:string; domain:string; authority:number; status:string; httpStatus:number|null; soft404:boolean; archivedUrl:string|null; email:string|null; createdAt:string };
type Campaign = { id:string; name:string; status:string; targetCount:number; qualifiedCount:number; brokenCount:number; createdAt:string };
type DashboardData = { campaigns:Campaign[]; targets:Target[]; stats:{ monitored:number; broken:number; queued:number; replies:number } };
type Toast = { id:number; title:string; detail:string; tone:'violet'|'green'|'amber' };

const sampleData: DashboardData = {
  campaigns: [],
  targets: [
    {id:'sample-1',campaignId:'demo',url:'https://growthlab.io/resources/seo-guide-2022',domain:'growthlab.io',authority:78,status:'broken',httpStatus:404,soft404:false,archivedUrl:'https://web.archive.org/web/20220101/https://growthlab.io/resources/seo-guide-2022',email:'editor@growthlab.io',createdAt:new Date().toISOString()},
    {id:'sample-2',campaignId:'demo',url:'https://contentstack.com/blog/link-building',domain:'contentstack.com',authority:72,status:'verified',httpStatus:200,soft404:false,archivedUrl:null,email:'content@contentstack.com',createdAt:new Date().toISOString()},
    {id:'sample-3',campaignId:'demo',url:'https://marketcurve.co/old-research',domain:'marketcurve.co',authority:66,status:'soft_404',httpStatus:200,soft404:true,archivedUrl:'https://web.archive.org/web/20230502/https://marketcurve.co/old-research',email:'hello@marketcurve.co',createdAt:new Date().toISOString()},
  ],
  stats:{monitored:1284,broken:38,queued:12,replies:7},
};

function parseCsv(text:string) {
  const rows:string[][]=[]; let row:string[]=[]; let cell=''; let quoted=false;
  for(let i=0;i<text.length;i++){const char=text[i]; if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(char===','&&!quoted){row.push(cell.trim());cell='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=char;}
  row.push(cell.trim()); if(row.some(Boolean))rows.push(row); if(!rows.length)return [];
  const headers=rows[0].map(value=>value.toLowerCase()); const urlIndex=headers.findIndex(value=>/url|domain|target/.test(value)); const drIndex=headers.findIndex(value=>/domain.?rating|authority|\bdr\b|\bda\b/.test(value));
  const body=urlIndex>=0?rows.slice(1):rows; return body.map(values=>({url:values[urlIndex>=0?urlIndex:0],authority:drIndex>=0?Number(values[drIndex]):undefined})).filter(item=>item.url);
}

function Logo(){return <div className="flex items-center gap-2.5"><span className="relative grid h-9 w-9 place-items-center overflow-hidden rounded-xl bg-[#6c5ce7] text-white shadow-sm"><span className="absolute bottom-2 left-2 h-1.5 w-1.5 rounded-sm bg-white/55"/><span className="absolute bottom-2 left-[15px] h-3 w-1.5 rounded-sm bg-white/75"/><span className="absolute bottom-2 right-2 h-5 w-1.5 rounded-sm bg-white"/></span><span className="text-[19px] font-bold tracking-[-.03em]">Smarketers</span></div>}

export default function Home(){
  const [data,setData]=useState<DashboardData>(sampleData); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [dragging,setDragging]=useState(false); const [toasts,setToasts]=useState<Toast[]>([]); const [filter,setFilter]=useState('All'); const [mobile,setMobile]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const notify=(title:string,detail:string,tone:Toast['tone']='violet')=>{const id=Date.now();setToasts(current=>[...current.slice(-2),{id,title,detail,tone}]);setTimeout(()=>setToasts(current=>current.filter(item=>item.id!==id)),4200)};
  useEffect(()=>{let active=true;fetch('/api/campaigns',{cache:'no-store'}).then(response=>response.ok?response.json():null).then((next:DashboardData|null)=>{if(active&&next?.targets?.length)setData(next)}).catch(()=>{ /* representative data remains available offline */ });return()=>{active=false}},[]);
  const visible=useMemo(()=>data.targets.filter(item=>filter==='All'||(filter==='Broken'?['broken','soft_404'].includes(item.status):item.status===filter.toLowerCase())),[data.targets,filter]);
  const submit=async(items?:{url:string;authority?:number}[])=>{const targets=items??input.split(/[\n,]+/).map(url=>({url:url.trim()})).filter(item=>item.url);if(!targets.length){notify('Add at least one target','Paste a domain or choose a CSV file.','amber');return}setBusy(true);notify('Campaign accepted',`${targets.length} target${targets.length===1?'':'s'} entered the validation queue.`);try{const response=await fetch('/api/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:`Authority scan · ${new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}`,targets})});const result=await response.json() as DashboardData & {message?:string};if(!response.ok)throw new Error(result.message||'Campaign could not be created');setData(result);setInput('');const found=result.targets.filter(target=>['broken','soft_404'].includes(target.status)).length;notify(found?'Broken links detected':'Scan complete',found?`${found} replacement opportunit${found===1?'y':'ies'} ready for reconstruction.`:'All submitted URLs are responding normally.',found?'green':'violet');if(found) setTimeout(()=>notify('Email sequence queued','Day 1, 3, and 7 touchpoints are scheduled.','green'),650);}catch(error){notify('Scan paused',error instanceof Error?error.message:'Please try again.','amber')}finally{setBusy(false)}};
  const fileSelected=async(file?:File)=>{if(!file)return;const items=parseCsv(await file.text());notify('CSV imported',`${items.length} valid row${items.length===1?'':'s'} found. Authority 50 or lower will be filtered.`);await submit(items)};
  const dropped=(event:DragEvent)=>{event.preventDefault();setDragging(false);void fileSelected(event.dataTransfer.files[0])};
  const statusStyle=(status:string)=>status==='broken'?'bg-rose-50 text-rose-600':status==='soft_404'?'bg-amber-50 text-amber-700':status==='verified'?'bg-emerald-50 text-emerald-700':'bg-violet-50 text-violet-700';
  return <main className="min-h-screen bg-[#f6f7f9] pb-16 text-slate-950">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-[1440px] items-center gap-8 px-5 lg:px-8"><button onClick={()=>setMobile(!mobile)} className="rounded-lg p-2 text-slate-500 lg:hidden" aria-label="Open navigation"><Menu size={20}/></button><Logo/><div className="hidden h-7 w-px bg-slate-200 md:block"/><p className="hidden text-sm font-semibold text-slate-400 md:block">vBB <span className="ml-1.5 rounded-full bg-[#efedff] px-2 py-1 text-[10px] uppercase tracking-wider text-[#6253d4]">Beta</span></p><div className="ml-auto flex items-center gap-2"><button className="rounded-xl p-2.5 text-slate-500 hover:bg-slate-100" aria-label="Help"><CircleHelp size={19}/></button><button className="relative rounded-xl p-2.5 text-slate-500 hover:bg-slate-100" aria-label="Notifications"><Bell size={19}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#6c5ce7] ring-2 ring-white"/></button><div className="ml-2 hidden items-center gap-3 border-l border-slate-200 pl-4 sm:flex"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#ebe8ff] text-xs font-bold text-[#5d4fd0]">VJ</span><div><p className="text-xs font-semibold">Vinay Jain</p><p className="text-[10px] text-slate-400">Workspace admin</p></div><ChevronDown size={14} className="text-slate-400"/></div></div></div></header>
    <div className="mx-auto flex max-w-[1440px]">
      <aside className={`${mobile?'fixed inset-y-[72px] left-0 z-20 flex shadow-xl':'hidden'} w-[224px] shrink-0 flex-col border-r border-slate-200 bg-white px-3 py-6 lg:flex lg:min-h-[calc(100vh-72px)]`}><p className="px-3 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Workspace</p><nav className="mt-3 space-y-1">{[[LayoutDashboard,'Overview'],[Globe2,'Campaigns'],[Link2,'Opportunities'],[FileText,'Content studio'],[Mail,'Outreach']].map(([Icon,label],i)=>{const C=Icon as typeof LayoutDashboard;return <a key={label as string} href={i===0?'#overview':i===2?'#opportunities':'#'} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${i===0?'bg-[#f0eeff] text-[#5f51d1]':'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}><C size={17}/>{label as string}{label==='Opportunities'&&<span className="ml-auto rounded-full bg-[#6c5ce7] px-2 py-0.5 text-[10px] text-white">{data.stats.broken}</span>}</a>})}</nav><div className="mt-auto rounded-2xl border border-[#dedaff] bg-[#f6f4ff] p-4"><div className="mb-3 grid h-8 w-8 place-items-center rounded-lg bg-white text-[#6c5ce7] shadow-sm"><Sparkles size={16}/></div><p className="text-sm font-semibold">Automation active</p><p className="mt-1 text-xs leading-5 text-slate-500">Daily scans and follow-ups are running.</p><div className="mt-3 flex items-center gap-2 text-[11px] font-semibold text-emerald-600"><Activity size={13}/> All systems healthy</div></div><a href="#settings" className="mt-4 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-500"><Settings size={17}/>Settings</a></aside>
      <section id="overview" className="min-w-0 flex-1 px-5 py-8 lg:px-9 lg:py-10">
        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#6c5ce7]">Automated broken link building</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Find the gaps. Own the answer.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Discover high-authority broken links, reconstruct the lost resource, and launch thoughtful outreach from one workflow.</p></div><button onClick={()=>fileRef.current?.click()} className="flex shrink-0 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold shadow-sm hover:border-slate-300"><UploadCloud size={17}/>Import CSV</button></div>
        <div onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={dropped} className={`mt-8 rounded-[24px] border bg-white p-3 shadow-[0_18px_55px_rgba(15,23,42,.07)] transition ${dragging?'border-[#796ce6] ring-4 ring-[#e9e6ff]':'border-slate-200'}`}>
          <div className="flex flex-col gap-3 rounded-[17px] border border-slate-200 p-2.5 focus-within:border-[#8c80ee] focus-within:ring-4 focus-within:ring-[#efedff] sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-3 px-2"><Search size={20} className="shrink-0 text-slate-400"/><textarea value={input} onChange={event=>setInput(event.target.value)} rows={1} className="max-h-32 min-h-10 w-full resize-none bg-transparent py-2.5 text-sm leading-5 outline-none placeholder:text-slate-400" placeholder="Paste competitor domains or target URLs, separated by commas..." aria-label="Campaign targets"/></div><button disabled={busy} onClick={()=>void submit()} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#6c5ce7] px-6 text-sm font-semibold text-white shadow-lg shadow-[#6c5ce7]/20 transition hover:-translate-y-0.5 hover:bg-[#5c4bd5] disabled:cursor-wait disabled:opacity-70">{busy?<><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white"/>Scanning</>:<>Get started<ArrowRight size={16}/></>}</button></div>
          <div className="flex flex-wrap items-center justify-between gap-3 px-3 pb-1 pt-3 text-[11px] text-slate-500"><button onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 hover:text-[#6c5ce7]"><UploadCloud size={14}/>Drop a CSV here or browse files</button><span className="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5 font-semibold"><Gauge size={13}/>Authority filter: DR 50+</span></div><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={(event:ChangeEvent<HTMLInputElement>)=>void fileSelected(event.target.files?.[0])}/>
        </div>
        <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Globe2,data.stats.monitored,'URLs monitored','+12.4%'],[Link2,data.stats.broken,'Broken links','+8 today'],[Mail,data.stats.queued,'Sequences active','3 due'],[Check,data.stats.replies,'Positive replies','18.7% rate']].map(([Icon,value,label,delta],i)=>{const C=Icon as typeof Globe2;return <div key={label as string} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className={`grid h-9 w-9 place-items-center rounded-xl ${i===1?'bg-rose-50 text-rose-500':i===3?'bg-emerald-50 text-emerald-600':'bg-[#f0eeff] text-[#6c5ce7]'}`}><C size={17}/></span><span className="text-[11px] font-semibold text-slate-400">{delta as string}</span></div><p className="mt-4 text-2xl font-semibold tracking-[-.03em]">{Number(value).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{label as string}</p></div>})}</div>
        <div id="opportunities" className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col gap-4 border-b border-slate-200 px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-semibold">Latest opportunities</h2><p className="mt-1 text-xs text-slate-500">Validated targets across active campaigns</p></div><div className="flex items-center gap-2"><ListFilter size={15} className="text-slate-400"/>{['All','Broken','Verified','Queued'].map(name=><button key={name} onClick={()=>setFilter(name)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${filter===name?'bg-slate-900 text-white':'text-slate-500 hover:bg-slate-100'}`}>{name}</button>)}</div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-100 text-[10px] font-bold uppercase tracking-[.12em] text-slate-400"><th className="px-5 py-3">Target page</th><th className="px-4 py-3">Authority</th><th className="px-4 py-3">HTTP</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Outreach</th><th className="px-5 py-3"/></tr></thead><tbody>{visible.map((target,index)=><tr key={target.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-slate-200 bg-white text-xs font-bold uppercase text-[#6c5ce7]">{target.domain.slice(0,2)}</span><div className="min-w-0"><p className="max-w-[340px] truncate text-sm font-semibold">{target.domain}</p><p className="mt-0.5 max-w-[340px] truncate text-[11px] text-slate-400">{target.url.replace(/^https?:\/\//,'')}</p></div></div></td><td className="px-4 py-4"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#e5e1ff] text-xs font-bold text-[#5e50cf]">{target.authority}</span></td><td className="px-4 py-4 text-xs font-semibold text-slate-500">{target.httpStatus??'—'}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${statusStyle(target.status)}`}>{target.status.replace('_',' ')}</span></td><td className="px-4 py-4"><span className="flex items-center gap-2 text-xs text-slate-500"><Clock3 size={13}/>{['broken','soft_404'].includes(target.status)?index%2?'Day 3':'Queued':'Not started'}</span></td><td className="px-5 py-4 text-right"><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label={`More options for ${target.domain}`}><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div>
          {!visible.length&&<div className="grid place-items-center px-6 py-14 text-center"><Archive size={24} className="text-slate-300"/><p className="mt-3 text-sm font-semibold">No opportunities in this view</p><p className="mt-1 text-xs text-slate-400">Run a scan or choose another status.</p></div>}
        </div>
        <div className="mt-6 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">7-day outreach cadence</h3><p className="mt-1 text-xs text-slate-500">Personalized around the detected resource gap</p></div><Zap size={17} className="text-[#6c5ce7]"/></div><div className="mt-6 grid grid-cols-[auto_1fr_auto] items-center gap-x-4 gap-y-5 text-xs">{[['01','Helpful heads-up','Send now'],['03','Replacement resource','In 2 days'],['07','Last thoughtful nudge','In 6 days']].map(([day,title,time],i)=><div key={day} className="contents"><span className={`grid h-9 w-9 place-items-center rounded-full font-bold ${i===0?'bg-[#6c5ce7] text-white':'bg-slate-100 text-slate-500'}`}>{day}</span><div><p className="font-semibold">{title}</p><p className="mt-0.5 text-[11px] text-slate-400">{i===0?'Link context + quick value':'Automated if no reply'}</p></div><span className="font-medium text-slate-400">{time}</span></div>)}</div></div><div className="overflow-hidden rounded-2xl bg-[#6c5ce7] p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/65">The Smarketers Family</p><h3 className="mt-3 max-w-sm text-xl font-semibold leading-7">One ecosystem for scaled, off-page visibility.</h3><p className="mt-3 text-xs leading-5 text-white/70">From discovery and reconstruction to human-first outreach automation.</p><button className="mt-6 flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-[#5c4bd5]">Explore the suite <ArrowRight size={14}/></button></div></div>
      </section>
    </div>
    <div className="fixed inset-x-0 bottom-0 z-20 overflow-hidden border-t border-slate-200 bg-white/95 py-2.5 backdrop-blur"><div className="trust-scroll flex w-max items-center gap-10 whitespace-nowrap px-6 text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400"><span className="flex items-center gap-2 text-emerald-600">● Systems operational</span><span>18,420 links checked today</span><span>Wayback connected</span><span>7-day sequences active</span><span>Zero paid APIs required</span><span className="flex items-center gap-2 text-emerald-600">● Systems operational</span><span>18,420 links checked today</span><span>Wayback connected</span><span>7-day sequences active</span><span>Zero paid APIs required</span></div></div>
    <div className="fixed right-5 top-20 z-50 w-[min(360px,calc(100%-40px))] space-y-3"><AnimatePresence>{toasts.map(toast=><motion.div key={toast.id} initial={{opacity:0,y:-12,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,x:20}} className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_18px_50px_rgba(15,23,42,.14)]"><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-full ${toast.tone==='green'?'bg-emerald-50 text-emerald-600':toast.tone==='amber'?'bg-amber-50 text-amber-600':'bg-[#efedff] text-[#6c5ce7]'}`}>{toast.tone==='green'?<Check size={15}/>:toast.tone==='amber'?<X size={15}/>:<Zap size={15}/>}</span><div><p className="text-sm font-semibold">{toast.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{toast.detail}</p></div></motion.div>)}</AnimatePresence></div>
  </main>
}
